In [1]:
import pandas as pd
import numpy as np

# Data Cleaning and Processing

In [2]:
F1 =  pd.read_csv('customer_churn_dataset-testing-master.csv')

In [3]:
F1.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,1,22,Female,25,14,4,27,Basic,Monthly,598,9,1
1,2,41,Female,28,28,7,13,Standard,Monthly,584,20,0
2,3,47,Male,27,10,2,29,Premium,Annual,757,21,0
3,4,35,Male,9,12,5,17,Premium,Quarterly,232,18,0
4,5,53,Female,58,24,9,2,Standard,Annual,533,18,0

In [4]:
F1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64374 entries, 0 to 64373
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         64374 non-null  int64
 1   Age                64374 non-null  int64
 2   Gender             64374 non-null  object
 3   Tenure             64374 non-null  int64
 4   Usage Frequency    64374 non-null  int64
 5   Support Calls      64374 non-null  int64
 6   Payment Delay      64374 non-null  int64
 7   Subscription Type  64374 non-null  object
 8   Contract Length    64374 non-null  object
 9   Total Spend        64374 non-null  int64
 10  Last Interaction   64374 non-null  int64
 11  Churn              64374 non-null  int64
dtypes: int64(9), object(3)
memory usage: 5.9+ MB

In [5]:
F2 =  F1.drop(['CustomerID'],axis = 'columns')

In [6]:
F2.head()

,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,22,Female,25,14,4,27,Basic,Monthly,598,9,1
1,41,Female,28,28,7,13,Standard,Monthly,584,20,0
2,47,Male,27,10,2,29,Premium,Annual,757,21,0
3,35,Male,9,12,5,17,Premium,Quarterly,232,18,0
4,53,Female,58,24,9,2,Standard,Annual,533,18,0

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [8]:
print(F2.columns)

Index(['Age', 'Gender', 'Tenure', 'Usage Frequency', 'Support Calls',
       'Payment Delay', 'Subscription Type', 'Contract Length', 'Total Spend',
       'Last Interaction', 'Churn'],
      dtype='object')

In [9]:
F2['Gender'] = le.fit_transform(F2['Gender'])
F2['Subscription Type'] = le.fit_transform(F2['Subscription Type'])
F2['Contract Length'] = le.fit_transform(F2['Contract Length'])

In [10]:
F2.head()

,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,22,0,25,14,4,27,0,1,598,9,1
1,41,0,28,28,7,13,2,1,584,20,0
2,47,1,27,10,2,29,1,0,757,21,0
3,35,1,9,12,5,17,1,2,232,18,0
4,53,0,58,24,9,2,2,0,533,18,0

In [11]:
F2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64374 entries, 0 to 64373
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                64374 non-null  int64
 1   Gender             64374 non-null  int32
 2   Tenure             64374 non-null  int64
 3   Usage Frequency    64374 non-null  int64
 4   Support Calls      64374 non-null  int64
 5   Payment Delay      64374 non-null  int64
 6   Subscription Type  64374 non-null  int32
 7   Contract Length    64374 non-null  int32
 8   Total Spend        64374 non-null  int64
 9   Last Interaction   64374 non-null  int64
 10  Churn              64374 non-null  int64
dtypes: int32(3), int64(8)
memory usage: 4.7 MB

# Datasplit

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X = F2.drop(['Churn'],axis = 'columns')
y = F2.Churn

In [14]:
X.head()

,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction
0,22,0,25,14,4,27,0,1,598,9
1,41,0,28,28,7,13,2,1,584,20
2,47,1,27,10,2,29,1,0,757,21
3,35,1,9,12,5,17,1,2,232,18
4,53,0,58,24,9,2,2,0,533,18

In [15]:
y

0        1
1        0
2        0
3        0
4        0
        ..
64369    1
64370    1
64371    1
64372    1
64373    1
Name: Churn, Length: 64374, dtype: int64

In [16]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2, random_state = 42)

In [17]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((51499, 10), (12875, 10), (51499,), (12875,))

In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

# Model Training using Tensorflow

In [20]:
import tensorflow as tf
from tensorflow import keras

In [21]:
model = keras.Sequential([
    keras.layers.Dense(64 , activation='relu',input_shape = (X_train.shape[1],)),
    keras.layers.Dropout(0.3),

    keras.layers.Dense(32 , activation='relu'),
    keras.layers.Dropout(0.3),

    keras.layers.Dense(1 , activation='sigmoid'),
])

model.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
)

C:\Users\Rahul\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [22]:
model.fit(X_train,y_train,validation_split=0.2,epochs = 10,batch_size= 32 , verbose = 1)

Epoch 1/10
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.8331 - loss: 0.3683 - val_accuracy: 0.8933 - val_loss: 0.2565
Epoch 2/10
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.8811 - loss: 0.2810 - val_accuracy: 0.9096 - val_loss: 0.2144
Epoch 3/10
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.8943 - loss: 0.2447 - val_accuracy: 0.9196 - val_loss: 0.1846
Epoch 4/10
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.9082 - loss: 0.2176 - val_accuracy: 0.9292 - val_loss: 0.1668
Epoch 5/10
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.9163 - loss: 0.1962 - val_accuracy: 0.9349 - val_loss: 0.1510
Epoch 6/10
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.9235 - loss: 0.1819 - val_accuracy: 0.9406 - val_loss: 0.1362
Epoch 7/10
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9290 - loss: 0.1682 - val_accuracy: 0.9472 - val_loss: 0.1265
Epoch 8/10
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.9347 - loss: 0.1577 - val_accuracy: 0.9566 - val_loss: 0.1143
Epoch 9/10
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.9402 - loss: 0.1475 - val_accuracy: 0.9642 - val_loss: 0.1023
Epoch 10/10
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.9462 - loss: 0.1375 - val_accuracy: 0.9652 - val_loss: 0.0960

In [23]:
model.evaluate(X_test,y_test)

403/403 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9649 - loss: 0.0931

[0.09314223378896713, 0.9648932218551636]

# Training using Pytorch

In [24]:
import os
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"

In [25]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader,Dataset,TensorDataset

In [26]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cuda

In [27]:
class CustomDataset(Dataset):
  def __init__(self,features,lables):

    self.features= torch.tensor(features,dtype = torch.float32)
    self.lables = torch.tensor(lables,dtype = torch.float32)

  def __len__(self):

    return len(self.features)

  def __getitem__(self,idx):

    return self.features[idx],self.lables[idx]

In [28]:
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32)

X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.float32)

train = TensorDataset(X_train_tensor, y_train_tensor)
test = TensorDataset(X_test_tensor, y_test_tensor)

In [29]:
class MYNN(nn.Module):
  def __init__(self,input_dim,output_dim,Number_of_hidden_layers,Neurons_per_layer,dropout_rate):
    super(MYNN,self).__init__()
    layers = []
    for i in range(Number_of_hidden_layers):
      layers.append(nn.Linear(input_dim,Neurons_per_layer))
      layers.append(nn.BatchNorm1d(Neurons_per_layer))
      layers.append(nn.ReLU())
      layers.append(nn.Dropout(dropout_rate))
      input_dim = Neurons_per_layer

    layers.append(nn.Linear(input_dim,output_dim))
    self.model = nn.Sequential(*layers)

  def forward(self,x):
    return self.model(x)

In [33]:
def objective(trial):
  num_hidden_layers = trial.suggest_int("num_hidden_layers", 1, 5)
  neurons_per_layer = trial.suggest_int("neurons_per_layer", 8, 128, step=8)
  learning_rate = trial.suggest_float("learning_rate", 1e-5, 1e-1, log=True)
  epochs = trial.suggest_int("epochs", 10,20, step=10)
  dropout_rate = trial.suggest_float("dropout_rate", 0.1, 0.5, step=0.1)
  batch_size = trial.suggest_categorical("batch_size", [16, 32, 64, 128])
  optimizer_name = trial.suggest_categorical("optimizer", ['Adam', 'SGD', 'RMSprop'])
  weight_decay = trial.suggest_float("weight_decay", 1e-5, 1e-3, log=True)

  train_loader  = DataLoader(train,batch_size = batch_size,shuffle = True)
  test_loader = DataLoader(test,batch_size = batch_size,shuffle = False)

  input_dim = X_train.shape[1]
  output_dim = 1
  model = MYNN(input_dim,output_dim,num_hidden_layers,neurons_per_layer,dropout_rate)
  model.to(device)


  # optimizer selection

  criterion = nn.BCEWithLogitsLoss()
  optimizer = optim.SGD(model.parameters(), lr=0.1, weight_decay=1e-4)



  if optimizer_name == 'Adam':
    optimizer = optim.Adam(model.parameters(), lr=learning_rate, weight_decay=weight_decay)
  elif optimizer_name == 'SGD':
    optim.SGD(model.parameters(), lr=learning_rate, weight_decay=weight_decay)
  else:
    optim.RMSprop(model.parameters(), lr=learning_rate, weight_decay=weight_decay)

  # Training loop

  for epoch in range(epochs):
    for batch_features,batch_lables in train_loader:
      batch_features = batch_features.to(device)
      batch_lables = batch_lables.to(device)

      # forward pass
      outputs = model(batch_features)

      # calculate loss
      loss = criterion(outputs.squeeze(-1),batch_lables.float())

      #back pass
      optimizer.zero_grad()
      loss.backward()

      # update grads
      optimizer.step()

  # evaluation
  model.eval()
  # evaluation on test data
  total = 0
  correct = 0

  with torch.no_grad():

    for batch_features, batch_labels in test_loader:

      # move data to gpu
      batch_features, batch_labels = batch_features.to(device), batch_labels.to(device)

      outputs = model(batch_features)

      predicted = (torch.sigmoid(outputs) > 0.5).int().squeeze(-1)

      total = total + batch_labels.shape[0]

      correct = correct + (predicted == batch_labels.int()).sum().item()

    accuracy = correct/total

  return accuracy

In [31]:
pip install optuna

Requirement already satisfied: optuna in c:\users\rahul\appdata\local\programs\python\python310\lib\site-packages (4.8.0)
Requirement already satisfied: alembic>=1.5.0 in c:\users\rahul\appdata\local\programs\python\python310\lib\site-packages (from optuna) (1.18.4)
Requirement already satisfied: colorlog in c:\users\rahul\appdata\local\programs\python\python310\lib\site-packages (from optuna) (6.10.1)
Requirement already satisfied: numpy in c:\users\rahul\appdata\local\programs\python\python310\lib\site-packages (from optuna) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\rahul\appdata\local\programs\python\python310\lib\site-packages (from optuna) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in c:\users\rahul\appdata\local\programs\python\python310\lib\site-packages (from optuna) (2.0.49)
Requirement already satisfied: tqdm in c:\users\rahul\appdata\local\programs\python\python310\lib\site-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in c:\users\rahul\appdata\local\programs\python\python310\lib\site-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in c:\users\rahul\appdata\local\programs\python\python310\lib\site-packages (from alembic>=1.5.0->optuna) (1.3.12)
Requirement already satisfied: typing-extensions>=4.12 in c:\users\rahul\appdata\local\programs\python\python310\lib\site-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: tomli in c:\users\rahul\appdata\local\programs\python\python310\lib\site-packages (from alembic>=1.5.0->optuna) (2.4.0)
Requirement already satisfied: greenlet>=1 in c:\users\rahul\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy>=1.4.2->optuna) (3.5.1)
Requirement already satisfied: colorama in c:\users\rahul\appdata\local\programs\python\python310\lib\site-packages (from colorlog->optuna) (0.4.6)
Requirement already satisfied: MarkupSafe>=0.9.2 in c:\users\rahul\appdata\local\programs\python\python310\lib\site-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

In [34]:
import optuna

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=10)

[I 2026-05-27 13:29:31,929] A new study created in memory with name: no-name-f4582ef8-afd3-4ef6-98de-eb711d6e0b10
[I 2026-05-27 13:31:09,879] Trial 0 finished with value: 0.9303300970873787 and parameters: {'num_hidden_layers': 4, 'neurons_per_layer': 80, 'learning_rate': 0.03303326658082468, 'epochs': 10, 'dropout_rate': 0.4, 'batch_size': 128, 'optimizer': 'SGD', 'weight_decay': 0.0009524093899894719}. Best is trial 0 with value: 0.9303300970873787.
[I 2026-05-27 13:36:38,931] Trial 1 finished with value: 0.9681553398058252 and parameters: {'num_hidden_layers': 4, 'neurons_per_layer': 64, 'learning_rate': 0.00021722007353124458, 'epochs': 20, 'dropout_rate': 0.2, 'batch_size': 64, 'optimizer': 'RMSprop', 'weight_decay': 2.3526159095269976e-05}. Best is trial 1 with value: 0.9681553398058252.
[I 2026-05-27 13:43:02,135] Trial 2 finished with value: 0.9350679611650485 and parameters: {'num_hidden_layers': 2, 'neurons_per_layer': 24, 'learning_rate': 0.00013872572537630934, 'epochs': 20, 'dropout_rate': 0.1, 'batch_size': 32, 'optimizer': 'Adam', 'weight_decay': 0.00023673560090112927}. Best is trial 1 with value: 0.9681553398058252.
[I 2026-05-27 13:44:40,603] Trial 3 finished with value: 0.9757669902912621 and parameters: {'num_hidden_layers': 3, 'neurons_per_layer': 64, 'learning_rate': 0.0004126944275735326, 'epochs': 20, 'dropout_rate': 0.1, 'batch_size': 128, 'optimizer': 'RMSprop', 'weight_decay': 0.0003938344662365716}. Best is trial 3 with value: 0.9757669902912621.
[I 2026-05-27 13:56:12,091] Trial 4 finished with value: 0.9704077669902913 and parameters: {'num_hidden_layers': 5, 'neurons_per_layer': 32, 'learning_rate': 0.0012744994092196763, 'epochs': 20, 'dropout_rate': 0.1, 'batch_size': 32, 'optimizer': 'Adam', 'weight_decay': 9.350082731337397e-05}. Best is trial 3 with value: 0.9757669902912621.
[I 2026-05-27 13:59:44,997] Trial 5 finished with value: 0.9697087378640776 and parameters: {'num_hidden_layers': 4, 'neurons_per_layer': 40, 'learning_rate': 0.0014303058309658124, 'epochs': 20, 'dropout_rate': 0.2, 'batch_size': 128, 'optimizer': 'SGD', 'weight_decay': 4.2802398806967764e-05}. Best is trial 3 with value: 0.9757669902912621.
[I 2026-05-27 14:22:35,274] Trial 6 finished with value: 0.9589126213592233 and parameters: {'num_hidden_layers': 5, 'neurons_per_layer': 56, 'learning_rate': 0.0034986486648549186, 'epochs': 20, 'dropout_rate': 0.1, 'batch_size': 16, 'optimizer': 'RMSprop', 'weight_decay': 3.4796982882316345e-05}. Best is trial 3 with value: 0.9757669902912621.
[I 2026-05-27 14:24:12,528] Trial 7 finished with value: 0.9606990291262136 and parameters: {'num_hidden_layers': 4, 'neurons_per_layer': 96, 'learning_rate': 8.011129751517385e-05, 'epochs': 10, 'dropout_rate': 0.2, 'batch_size': 128, 'optimizer': 'SGD', 'weight_decay': 2.711084984667281e-05}. Best is trial 3 with value: 0.9757669902912621.
[I 2026-05-27 14:26:02,426] Trial 8 finished with value: 0.8464466019417476 and parameters: {'num_hidden_layers': 1, 'neurons_per_layer': 96, 'learning_rate': 1.2946494913961673e-05, 'epochs': 10, 'dropout_rate': 0.30000000000000004, 'batch_size': 64, 'optimizer': 'Adam', 'weight_decay': 0.0007076503796967274}. Best is trial 3 with value: 0.9757669902912621.
[I 2026-05-27 14:28:48,733] Trial 9 finished with value: 0.9381747572815534 and parameters: {'num_hidden_layers': 3, 'neurons_per_layer': 56, 'learning_rate': 0.0017599791588221564, 'epochs': 20, 'dropout_rate': 0.5, 'batch_size': 128, 'optimizer': 'SGD', 'weight_decay': 2.1847715657474457e-05}. Best is trial 3 with value: 0.9757669902912621.

In [35]:
print(f'best params : {study.best_params}')
print(f'best value : {study.best_value}')

best params : {'num_hidden_layers': 3, 'neurons_per_layer': 64, 'learning_rate': 0.0004126944275735326, 'epochs': 20, 'dropout_rate': 0.1, 'batch_size': 128, 'optimizer': 'RMSprop', 'weight_decay': 0.0003938344662365716}
best value : 0.9757669902912621

In [36]:
study.best_params

{'num_hidden_layers': 3,
 'neurons_per_layer': 64,
 'learning_rate': 0.0004126944275735326,
 'epochs': 20,
 'dropout_rate': 0.1,
 'batch_size': 128,
 'optimizer': 'RMSprop',
 'weight_decay': 0.0003938344662365716}